name: Java CI/CD Pipeline to Tomcat

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # 3. Check project files
      - name: Check project
        run: |
          pwd
          ls -la
          ls -la github-actions-project-6pm-main
          find github-actions-project-6pm-main -name "pom.xml"

      # 4. Build with Maven
      - name: Build with Maven
        working-directory: ./github-actions-project-6pm-main
        run: mvn clean package -DskipTests

      # 5. Upload WAR artifact
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: github-actions-project-6pm-main/target/*.war


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:

      # 6. Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      # 7. Check WAR
      - name: Check WAR file
        run: |
          ls -la
          ls -la *.war

      # 8. Deploy WAR to Tomcat
      - name: Deploy WAR to Tomcat
        run: |
          WAR_FILE=$(ls *.war)

          echo "Deploying $WAR_FILE to Tomcat..."

          curl -v \
            -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
            --upload-file "$WAR_FILE" \
            "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"
